language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
before_install:
  - gem install bundler -v `grep -A1 'BUNDLED WITH' Gemfile.lock | tail -1`
script:
  - bundle exec rubocop --fail-fast
  - bundle exec rake
